spring:
  application:
    name: arquivo

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        concurrency: 3
        max-concurrency: 10
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          multiplier: 2.0

aws:
  s3:
    bucket: ${AWS_S3_BUCKET}
    region: ${AWS_REGION}

app:
  rabbit:
    exchange: file.exchange
    queue: file.upload.queue
    routing-key: file.upload